### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by tqangxl** [dowsnature/dowsDNS#40]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。
C:\Users\xxx>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default,
-------------------------------------

========================**
当前可用操作有：
  1 运行本地DNS服务器
  2 恢复动态DNS(恢复网络)
  3 更新记录文件并运行本地DNS服务器
  4 退出
请选择后回车：
3

Windows IP 配置
已成功刷新 DNS 解析缓存。
Sorry,DNSMasq is not support
Traceback (most recent call last):
  File "update.py", line 60, in <module>
urllib2.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
Failed to execute script update
若无法使用,请手动修改系统的DNS为:127.0.0.1(默认情况)
==========Config===========
Local_dns_server: 127.0.0.1
Local_dns_port: 53
Remote_dns_server: 114.114.114.114
Remote_dns_port: 53
===========Config==========
Trying start bind local IP and port ...
Bind successfully! Running ...
Query:  clients2.google.com.
Revise: clients2.google.com.
Query:  www.google.com.
Revise: www.google.com.
Query:  Query:  mail.google.com.mail.google.com.

**Comment by downature** [comment]
系统DNS改为114.114.114.114
python update.py
start.py
更改系统DNS 为127.0.0.1

**Comment by hdjdm** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\j>d:

D:\>cd dowsDNS-beta

D:\dowsDNS-beta>python start.py
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\dowsDNS-beta>py start.py
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

D:\dowsDNS-beta>py update.py
Starting hosts updating...
success! hosts  have done !
Starting  wrcd  updating...
success!  wrcd  have done !

D:\dowsDNS-beta>py start.py
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

D:\dowsDNS-beta>
