### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by beesuns** [dowsnature/dowsDNS#48]
sudo python start.py
Password:
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ImportError: No module named requests
MacBook-Air:dowsDNS-beta $

**Comment by chensongbin** [comment]
pip install requests

**Comment by wangweiguo2013** [comment]
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by import-yuefeng** [comment]
your should use pip (python package manager) to install requests.
example:
  pip install requests    or
  pip3 install requests
