### ISSUE TITLE
  3 更新记录文件并运行本地DNS服务器----一直显示错误，无法运用更新功能

### ISSUE THREAD

**Issue by ghost** [dowsnature/dowsDNS#59]
错误信息如下：
需要管理员权限运行此脚本
========================
当前可用操作有：
  1 运行本地DNS服务器
  2 恢复动态DNS(恢复网络)
  3 更新记录文件并运行本地DNS服务器
  4 退出
请选择后回车：
3

Windows IP 配置

已成功刷新 DNS 解析缓存。
Sorry,DNSMasq is not support
Traceback (most recent call last):
  File "update.py", line 60, in <module>
urllib2.HTTPError: HTTP Error 404: Not Found
Failed to execute script update
若无法使用,请手动修改系统的DNS为:127.0.0.1(默认情况)
==========Config===========
Local_dns_server: 127.0.0.1
Local_dns_port: 53
Remote_dns_server: 114.114.114.114
Remote_dns_port: 53
===========Config==========
Trying start bind local IP and port ...
Bind successfully! Running ...
Query:  thuth-sg.tlsext.com.

一直显示：
Traceback (most recent call last):
  File "update.py", line 60, in <module>
urllib2.HTTPError: HTTP Error 404: Not Found
连接错误

**Comment by firstlight101** [comment]
解决了吗？怎么解决的啊
